### ISSUE TITLE
Update data.js

### ISSUE THREAD

**Issue by sylwiavargas** [sruti/covid19-riskfactors-app#29]
- [x] Under mortality for hypertension, diabetes, and CAD you don't have to say 'per unit increase'
- [x] Let's remove Glucose from the whole thing
- [x] Update labels: excel sheet under the tab LABELS UPDATED (I only included highlighted boxes for new stuff, the rest stays the way it currently is.)
- [x] add new study (email from 3/31)
- [x] everything in the labs should have an up arrow except for leuko and lympho

**Comment by sylwiavargas** [comment]
@sruti there's no leuko + "everything in the labs should have an up arrow except for leuko and lympho" -> the titles or the RatioTitles?

**Comment by sylwiavargas** [comment]
In legend for the new study, there's no ratio explanation

**Comment by sruti** [comment]
Only thing left for the new study is adding in the text in parentheses below (from the email), but I'll do that when working on #30 

Age  p=<0.001 66 (57-78) vs. 51 (37-62) 
Hypertension  p=<0.001 
CAD p=<0.04
Diabetes p=0.009
Dyspnea p=<0.05

Lymphopenia p=<0.03 0.8 (0.5-0.9) vs. 0.9 (0.6-1.2)
Elevated d-Dimer (mg/L) p=<0.001 414 (191-1324) vs. 166 (101-285)
Elevated LDH (U/L) p=<0.001 435 (302-596) vs. 212 (171-291)
Elevated AST/ALT (U/L) p=<0.05 
Total Bilirubin (mmol/L) p=0.02 11.5 (9.6-18.6) vs. 9.3 (8.2-12.8)
Cr (umol/L) p=0.04  80 (66-106) vs. 71 (58-84)
hs-Trop (pg/mL) p=0.004 11.0 (5.6-26.4) vs. 5.1 (2.1-9.8)
Procalcitonin >/=0.05 (ng/mL) p=<0.001
