### ISSUE TITLE
when changing tabs, all the children state should be false

### ISSUE THREAD

**Issue by sylwiavargas** [sruti/covid19-riskfactors-app#37]
@sruti

**Comment by sruti** [comment]
Oh I see where this is happening. If you click on a child, unclick the parent, switch tabs, the parent is unclicked but when you click it, instead of the child having both yes and no unclicked, it's keeping whatever was there on the previous tab. Didn't get a chance to fix this yet.

**Comment by sylwiavargas** [comment]
I just set it up in a way that it will reset now with each tab change.

**Comment by sylwiavargas** [comment]
If age is unclicked then age y/n should also be false
